image: ghcr.io/jethub-homeassistant/{arch}-homeassistant-base
build_from:
  aarch64: ghcr.io/jethub-homeassistant/aarch64-base-python:3.12-alpine3.19
  armhf: ghcr.io/jethub-homeassistant/armhf-base-python:3.12-alpine3.19
  armv7: ghcr.io/jethub-homeassistant/armv7-base-python:3.12-alpine3.19
  amd64: ghcr.io/jethub-homeassistant/amd64-base-python:3.12-alpine3.19
  i386: ghcr.io/jethub-homeassistant/i386-base-python:3.12-alpine3.19
codenotary:
  signer: vb@jethome.ru
  base_image: vb@jethome.ru
cosign:
  base_identity: https://github.com/jethub-homeassistant/docker-base/.*
  identity: https://github.com/jethub-homeassistant/docker/.*
labels:
  io.hass.type: homeassistant-base
  org.opencontainers.image.title: JH Home Assistant Core baseimage
  org.opencontainers.image.description: Baseimage for Home Assistant Core container/supervisor installation
  org.opencontainers.image.source: https://github.com/jethub-homeassistant/docker
  org.opencontainers.image.authors: The Home Assistant Authors (JetHome patched)
  org.opencontainers.image.url: https://www.home-assistant.io/
  org.opencontainers.image.documentation: https://www.home-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
args:
  SSOCR_VERSION: 2.22.1
  LIBCEC_VERSION: 6.0.2
  TELLDUS_COMMIT: 2598bbed16ffd701f2a07c99582f057a3decbaf3
  PICOTTS_HASH: e3ba46009ee868911fa0b53db672a55f9cc13b1c
